### ISSUE TITLE
When source has changed markers should be cleared.

### ISSUE THREAD

**Issue by asampal** [ccw-ide/ccw-plugin-eastwood#9]
I was testing out this plugin and created a doubly defined form. I got the expected marker after invoking this plugin. I changed the source so that the form was no longer defined twice, saved the editor and re-loaded into the REPL. The marker created by Eastwood remained even though it was no longer valid.

I would say that, Eastwood created markers should be cleared when source is modified and saved since the indicated problems might not be valid any longer. Of course if Eastwood were automatically re-invoked the state of the markers would be more accurate, but that action is too time-consuming to be performed automatically.

**Comment by laurentpetit** [comment]
OK, thanks for the report, I don't use eastwood plugin myself that much (I probably should!).

So if I understand correctly, you're saying that relaunching eastwood is too time consuming if done everytime a file is saved, but the plugin should remove all eastwood markers for files that are edited then saved?
If I'm right, are you suggesting that these markers be cleared for all files, or just that one file?

Another idea out of the top of my head: if there were a way to keep the eastwood markers, but indicate that they may be invalid (for instance, changing their color, or I don't know what, maybe also some text after or before the eastwood text), would that be better, or not? If not necessarily better, then it's definitely simpler to just remove the markers.

**Comment by asampal** [comment]
Ideally any files that have been edited and which have markers created by Eastwood should be cleared. If possible, only the Eastwood-created markers should be cleared, but I'm guessing this is not tracked. 

On my system, Eastwood seems to take about 10s-15s to do the analysis. I'm not sure if there's any caching done to save time on subsequent invocations.

Your idea sounds pretty good, if you can show their possible invalidity in an obvious way. I think I'd prefer this over outright clearing since there is a good chance that not all markers would become invalid by the editing. When you say to add some text before or after the Eastwood text, do you mean the text in the tooltip for the markers? If so, yes, that would be a good solution.

**Comment by laurentpetit** [comment]
Playing with it right now.
I can see that it is long to execute. Part of it being the time spent by leiningen, part of it being the time of the tool itself.
Of course, if there was already an active repl for this project, if the project already embedded eastwood and if it was easy to find the right repl for the project, then we could launch eastwood from within the repl started by the user.
Or we could just assume that the active REPL is the one in which we want to launch eastwood, and just try to require the eastwood namespace. If no eastwood namespace, then a popup informs the user.

What do you think?

**Comment by laurentpetit** [comment]
FYI, this is the alternative approach I'm trying with the core.typed plugin, just so in the end both alternatives are available to user plugins and have easy API to work with from CCW

**Comment by asampal** [comment]
That sounds like a reasonable approach, Laurent. If there will be a need for a UI here the specifics of that should become evident after some use.

**Comment by laurentpetit** [comment]
I have fixed an outstanding issue wrt how dynamic contribution ids are managed. This prevented consistent management of markers type-ids.
Now, the master branch of ccw-plugin-eastwood requires a CCW version > 0.32.0, meaning you'll have to follow the master version of CCW if you merge from `ccw-ide/ccw-plugin-eastwood`

**Comment by laurentpetit** [comment]
Now, this was just a preparation of the current issue, which required specific targetting for markers removals. Now that it's out of the way, I'll be able to work on it again.

**Comment by laurentpetit** [comment]
Requires the master build CI0403 which will hopefully appear succesfully here thanks to Jenkins: http://updatesite.ccw-ide.org/branch/master/

**Comment by laurentpetit** [comment]
Adrian, if you find time to give your ideas wrt the current "API"s that are used from user plugins,especially ccw-plugin-eastwood, it would be a great feedback. Because I feel like suffering from the "knowledge curse": I may find easy-to-use / straightforward stuff that is really unclear to you.

**Comment by laurentpetit** [comment]
@asampal do you think this eastwood plugin is stable enough to be embedded in ccw by default ?

**Comment by asampal** [comment]
I've been on vacation for the last few weeks so I haven't had a chance to really look things over, Laurent. Should be back home in the last week of August and I'll try and give you feedback then.
